#!/usr/bin/env python3
"""Build polished plots and LaTeX tables for the RF-LR symmetry workshop paper."""
from __future__ import annotations

import csv
import json
import math
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "results" / "multidim_batch1_symmetry"
OUT = ROOT / "results" / "paper_assets"
EPS = 1e-12


def apply_style() -> None:
    plt.rcParams["figure.figsize"] = [3.35, 2.55]
    plt.rcParams["font.size"] = 8
    plt.rcParams["font.weight"] = "normal"
    mpl.rcParams["mathtext.fontset"] = "cm"
    mpl.rcParams["mathtext.rm"] = "serif"
    mpl.rcParams["savefig.dpi"] = 450
    mpl.rcParams["font.size"] = 8
    mpl.rcParams["axes.formatter.limits"] = (-6, 6)
    mpl.rcParams["axes.formatter.use_mathtext"] = True
    mpl.rcParams["font.family"] = "DejaVu Serif"
    mpl.rcParams["xtick.minor.visible"] = True
    mpl.rcParams["ytick.minor.visible"] = True
    mpl.rcParams["axes.linewidth"] = 0.65
    mpl.rcParams["xtick.major.width"] = 0.55
    mpl.rcParams["ytick.major.width"] = 0.55
    mpl.rcParams["xtick.minor.width"] = 0.45
    mpl.rcParams["ytick.minor.width"] = 0.45
    mpl.rcParams["legend.frameon"] = False
    plt.rcParams["ytick.right"] = False
    plt.rcParams["xtick.top"] = False
    plt.rcParams["axes.spines.top"] = False
    plt.rcParams["axes.spines.right"] = False


def read_rows() -> list[dict]:
    rows = []
    for path in sorted(RESULTS.glob("*/metrics.json")):
        with open(path) as f:
            row = json.load(f)
        rows.append(row)
    return rows


def value(row: dict, key: str) -> float:
    try:
        return float(row.get(key, np.nan))
    except (TypeError, ValueError):
        return float("nan")


def is_main_row(row: dict) -> bool:
    return (
        row.get("model") == "mmnn"
        and int(row.get("width", 0)) == 512
        and str(row.get("optimizer", "")) == "adam"
        and str(row.get("train_distribution", "")) == "unpaired_uniform"
        and int(row.get("freq", 0)) == 1
    )


def display_arch(row: dict) -> str:
    model = str(row.get("model", ""))
    if model == "mlp":
        return "MLP"
    rank = int(row.get("rank", 0))
    width = int(row.get("width", 1))
    return f"RF-LR {rank}/{width}"


def sci(x: float) -> str:
    if not np.isfinite(x):
        return "--"
    if x == 0:
        return "$0$"
    exponent = int(np.floor(np.log10(abs(x))))
    mantissa = x / (10 ** exponent)
    return f"${mantissa:.2f}\\!\\times\\!10^{{{exponent}}}$"


def bold_sci(x: float) -> str:
    if not np.isfinite(x):
        return "--"
    if x == 0:
        return "$\\boldsymbol{0}$"
    exponent = int(np.floor(np.log10(abs(x))))
    mantissa = x / (10 ** exponent)
    return f"$\\boldsymbol{{{mantissa:.2f}\\!\\times\\!10^{{{exponent}}}}}$"


def maybe_bold_sci(x: float, best_value: float) -> str:
    if np.isfinite(x) and np.isfinite(best_value) and np.isclose(x, best_value, rtol=1e-12, atol=1e-18):
        return bold_sci(x)
    return sci(x)


def write_aggregate(rows: list[dict]) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    fields = sorted({key for row in rows for key in row.keys()})
    with open(OUT / "all_metrics_aggregate.csv", "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    with open(OUT / "all_metrics_aggregate.json", "w") as f:
        json.dump(rows, f, indent=2)


def select_best_rows(rows: list[dict]) -> list[dict]:
    candidates = [
        row for row in rows
        if is_main_row(row)
        and int(row.get("rank", 0)) in {8, 16, 64, 128}
        and str(row.get("target")) in {"gaussian", "quadratic", "soft_axis"}
    ]
    best_by_key: dict[tuple, dict] = {}
    for row in candidates:
        key = (int(row["dim"]), str(row["target"]), int(row["rank"]))
        current = best_by_key.get(key)
        if current is None or value(row, "best_test_mse") < value(current, "best_test_mse"):
            best_by_key[key] = row
    return sorted(best_by_key.values(), key=lambda r: (int(r["dim"]), str(r["target"]), int(r["rank"])))


def write_tables(rows: list[dict]) -> None:
    reps = representative_result_rows(rows)
    reps = [
        row for row in reps
        if (int(row.get("dim", 0)), str(row.get("target")), int(row.get("rank", 0))) in {
            (2, "gaussian", 8),
            (2, "quadratic", 8),
            (3, "quadratic", 8),
            (2, "quadratic", 128),
            (3, "quadratic", 128),
        }
    ]
    with open(ROOT / "tables_generated.tex", "w") as f:
        f.write("% Auto-generated by build_paper_assets.py\n")
        f.write("\\vspace{0.1em}\n\\begin{center}\\scriptsize\n")
        f.write("\\setlength{\\tabcolsep}{2.5pt}\n")
        f.write("\\renewcommand{\\arraystretch}{1.05}\n")
        f.write("\\captionof{table}{Multidimensional batch-one protocol and representative results. No $(x,-x)$ pair is inserted during training; symmetry metrics are post-hoc on a separate symmetric grid.}\n")
        f.write("\\label{tab:method-summary}\n")
        f.write("\\resizebox{\\linewidth}{!}{%\n")
        f.write("\\begin{tabular}{@{}llcccc@{}}\\toprule\n")
        f.write("Data & model & rank & test MSE & $D_{out}$ & active $D_p$ \\\\\\midrule\n")
        for row in reps:
            target = str(row.get("target", "")).replace("gaussian", "Gauss.").replace("quadratic", "Quad.")
            data = f"{int(row['dim'])}D {target}"
            rank = int(row.get("rank", 0))
            model = "RF-LR" if rank in {8, 16} else "RF-LR ctrl."
            f.write(
                f"{data} & {model} & {rank} & "
                f"{sci(value(row, 'best_test_mse'))} & "
                f"{sci(value(row, 'best_output_neg_defect'))} & "
                f"{sci(value(row, 'best_last_partial_neg_defect'))} \\\\\n"
            )
        f.write("\\midrule\n")
        f.write("\\multicolumn{6}{@{}l@{}}{All rows: $W=512$, Adam $10^{-3}$, $10k$ epochs, batch $1$; frozen $A^{(\\ell)},b^{(\\ell)}$, train only $B^{(\\ell)}$.} \\\\\n")
        f.write("\\bottomrule\\end{tabular}%\n}\n\\end{center}\n\n")


def representative_result_rows(rows: list[dict]) -> list[dict]:
    best = select_best_rows(rows)
    low_rows = [
        row for row in best
        if (int(row["dim"]), str(row["target"]), int(row["rank"])) in {
            (2, "gaussian", 8), (2, "quadratic", 8), (2, "soft_axis", 8), (3, "quadratic", 8)
        }
    ]
    high_rows = [
        row for row in best
        if int(row.get("rank", 0)) in {64, 128}
        and str(row.get("target")) == "quadratic"
        and int(row.get("dim", 0)) in {2, 3}
    ]
    return low_rows + high_rows


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def csv_value(row: dict[str, str], key: str) -> float:
    try:
        return float(row.get(key, "nan"))
    except (TypeError, ValueError):
        return float("nan")


def plot_sumcos_targets() -> None:
    x = np.linspace(-1.0, 1.0, 1600)
    targets = [
        ("smooth", [(1.00, 2.0), (-0.35, 5.0), (0.18, 9.0)]),
        ("hard", [(0.70, 16.0), (-0.48, 32.0), (0.32, 52.0), (-0.20, 76.0)]),
    ]
    colors = ["#1B9E77", "#D95F02"]
    fig, axes = plt.subplots(1, 2, figsize=(3.35, 1.42), sharex=True, sharey=True)
    for ax, (label, terms), color in zip(axes, targets, colors):
        y = np.zeros_like(x)
        for alpha, omega in terms:
            y += alpha * np.cos(np.pi * omega * x)
        y = y / (np.max(np.abs(y)) + EPS)
        ax.plot(x, y, color=color, linewidth=1.0)
        ax.axvline(0.0, color="#222222", linewidth=0.45, alpha=0.35)
        ax.set_title(label, fontsize=8, pad=1.5)
        ax.set_xlabel("$x$")
        ax.set_xlim(-1.0, 1.0)
        ax.set_ylim(-1.08, 1.08)
        ax.set_xticks([-1.0, 0.0, 1.0])
        ax.set_yticks([-1.0, 0.0, 1.0])
        ax.grid(True, which="major", color="#D9D9D9", linewidth=0.4, alpha=0.75)
    axes[0].set_ylabel("target")
    fig.tight_layout(pad=0.18, w_pad=0.55)
    fig.savefig(OUT / "paper_sumcos_targets.png", bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)


def plot_sumcos_low_loss() -> None:
    rows = read_csv_rows(ROOT / "results" / "good_sumcos_low_loss" / "summary.csv")
    rows = [row for row in rows if np.isfinite(csv_value(row, "final_test_error"))]
    if not rows:
        return
    fig, ax = plt.subplots(figsize=(3.35, 2.05))
    palette = {5: "#2A6FBB", 10: "#D95F02"}
    for row in rows:
        rank = int(csv_value(row, "rank"))
        ax.scatter(
            csv_value(row, "final_test_error"),
            csv_value(row, "last_layer_active_even_mean") + EPS,
            s=34,
            color=palette.get(rank, "#666666"),
            edgecolor="white",
            linewidth=0.5,
            zorder=3,
        )
    best = min(rows, key=lambda row: csv_value(row, "last_layer_active_even_mean"))
    ax.scatter(
        csv_value(best, "final_test_error"),
        csv_value(best, "last_layer_active_even_mean") + EPS,
        s=62,
        facecolor="none",
        edgecolor="#111111",
        linewidth=1.0,
        zorder=4,
    )
    ax.annotate(
        "best partial",
        xy=(csv_value(best, "final_test_error"), csv_value(best, "last_layer_active_even_mean") + EPS),
        xytext=(5, 8),
        textcoords="offset points",
        fontsize=7,
    )
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("test MSE")
    ax.set_ylabel("partial even defect")
    ax.grid(True, which="major", color="#D9D9D9", linewidth=0.45, alpha=0.8)
    ax.grid(True, which="minor", color="#EEEEEE", linewidth=0.25, alpha=0.5)
    handles = [
        plt.Line2D([], [], marker="o", linestyle="", color=palette[5], markeredgecolor="white", label="rank 5"),
        plt.Line2D([], [], marker="o", linestyle="", color=palette[10], markeredgecolor="white", label="rank 10"),
    ]
    ax.legend(handles=handles, loc="upper right", fontsize=7)
    fig.tight_layout(pad=0.25)
    fig.savefig(OUT / "paper_sumcos_low_loss.png", bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)


def plot_weightspace_regimes() -> None:
    rows = read_csv_rows(ROOT / "results" / "weightspace_distributions" / "weightspace_classification.csv")
    rows = [
        row for row in rows
        if np.isfinite(csv_value(row, "final_test_error"))
        and np.isfinite(csv_value(row, "last_layer_active_even_mean"))
    ]
    if not rows:
        return
    order = ["partial-symmetric", "output-only/asymmetric", "intermediate", "underfit"]
    colors = {
        "partial-symmetric": "#1B9E77",
        "output-only/asymmetric": "#D95F02",
        "intermediate": "#7570B3",
        "underfit": "#8C8C8C",
    }
    labels = {
        "partial-symmetric": "partial-sym.",
        "output-only/asymmetric": "output-only",
        "intermediate": "intermediate",
        "underfit": "underfit",
    }
    rank_markers = {5: "o", 10: "s"}
    fig, ax = plt.subplots(figsize=(3.35, 2.28))
    for label in order:
        for rank, marker in rank_markers.items():
            subset = [row for row in rows if row.get("class") == label and int(csv_value(row, "rank")) == rank]
            if not subset:
                continue
            x = np.asarray([csv_value(row, "final_test_error") for row in subset])
            y = np.asarray([csv_value(row, "last_layer_active_even_mean") for row in subset])
            mismatch = np.asarray([csv_value(row, "mirror_mismatch_median") for row in subset])
            size = 20 + 16 * np.clip(mismatch, 0.0, 1.2)
            ax.scatter(
                x,
                y + EPS,
                s=size,
                marker=marker,
                color=colors[label],
                alpha=0.72,
                edgecolor="white",
                linewidth=0.35,
            )
    ax.axhline(1e-3, color="#222222", linestyle="--", linewidth=0.65, alpha=0.7)
    ax.axvline(1e-3, color="#222222", linestyle="--", linewidth=0.65, alpha=0.7)
    ax.text(1.15e-5, 3.7e0, "RF-LR low-rank", fontsize=6.6, va="top")
    ax.text(1.15e-5, 8.0e-1, "larger dots = larger\nweight mirror mismatch", fontsize=5.9, va="top")
    ax.text(1.15e-5, 1.25e-3, "partial threshold", fontsize=6.5, va="bottom")
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("test MSE")
    ax.set_ylabel("partial even defect")
    ax.grid(True, which="major", color="#D9D9D9", linewidth=0.45, alpha=0.8)
    ax.grid(True, which="minor", color="#EEEEEE", linewidth=0.25, alpha=0.5)
    color_handles = [
        plt.Line2D([], [], marker="o", linestyle="", color=colors[label], markeredgecolor="white", label=labels[label])
        for label in order
    ]
    rank_handles = [
        plt.Line2D([], [], marker=marker, linestyle="", color="#555555", markeredgecolor="white", label=f"rank {rank}")
        for rank, marker in rank_markers.items()
    ]
    first_legend = ax.legend(handles=color_handles, loc="lower right", fontsize=5.8, ncol=1, handletextpad=0.15, borderpad=0.08)
    ax.add_artist(first_legend)
    ax.legend(handles=rank_handles, loc="upper right", fontsize=5.8, handletextpad=0.15, borderpad=0.08)
    fig.tight_layout(pad=0.18)
    fig.savefig(OUT / "paper_weightspace_regimes.png", bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)


def plot_weightspace_class_summary() -> None:
    rows = read_csv_rows(ROOT / "results" / "weightspace_distributions" / "weightspace_classification.csv")
    rows = [row for row in rows if row.get("class")]
    if not rows:
        return
    order = ["partial-symmetric", "output-only/asymmetric", "intermediate", "underfit"]
    colors = {
        "partial-symmetric": "#1B9E77",
        "output-only/asymmetric": "#D95F02",
        "intermediate": "#7570B3",
        "underfit": "#8C8C8C",
    }
    counts = [sum(row.get("class") == label for row in rows) for label in order]
    med_partial = [
        np.nanmedian([csv_value(row, "last_layer_active_even_mean") for row in rows if row.get("class") == label])
        for label in order
    ]
    med_mismatch = [
        np.nanmedian([csv_value(row, "mirror_mismatch_median") for row in rows if row.get("class") == label])
        for label in order
    ]
    labels = ["partial\nsym.", "output\nonly", "interm.", "underfit"]
    fig, axes = plt.subplots(1, 3, figsize=(3.35, 1.62))
    x = np.arange(len(order))
    axes[0].bar(x, counts, color=[colors[o] for o in order], edgecolor="white", linewidth=0.4)
    axes[0].set_ylabel("runs", fontsize=7)
    axes[0].set_xticks(x, labels, fontsize=5.8)
    axes[0].set_title("149 checkpoints", fontsize=7.2, pad=1.2)
    axes[1].bar(x, np.asarray(med_partial) + EPS, color=[colors[o] for o in order], edgecolor="white", linewidth=0.4)
    axes[1].set_yscale("log")
    axes[1].set_xticks(x, labels, fontsize=5.8)
    axes[1].set_title("median $D_p$", fontsize=7.2, pad=1.2)
    axes[2].bar(x, np.asarray(med_mismatch) + EPS, color=[colors[o] for o in order], edgecolor="white", linewidth=0.4)
    axes[2].set_yscale("log")
    axes[2].set_xticks(x, labels, fontsize=5.8)
    axes[2].set_title("mirror mismatch", fontsize=7.2, pad=1.2)
    for ax in axes:
        ax.tick_params(axis="y", labelsize=5.8, length=2.0)
        ax.grid(True, axis="y", which="major", color="#D9D9D9", linewidth=0.35, alpha=0.75)
    fig.tight_layout(pad=0.08, w_pad=0.35)
    fig.savefig(OUT / "paper_weightspace_class_summary.png", bbox_inches="tight", pad_inches=0.012)
    plt.close(fig)


def row_best(row: dict, key: str) -> float:
    best = value(row, f"best_{key}")
    if np.isfinite(best):
        return best
    return value(row, key)


def model_group(row: dict) -> str:
    if str(row.get("model")) == "mlp":
        return "MLP"
    rank = int(row.get("rank", 0))
    if rank <= 16:
        return "RF-LR low"
    if rank >= 64:
        return "RF-LR high"
    return "RF-LR mid"


def finite_metric_rows(rows: list[dict]) -> list[dict]:
    return [
        row for row in rows
        if np.isfinite(row_best(row, "test_mse"))
        and np.isfinite(row_best(row, "last_partial_neg_defect"))
        and str(row.get("target", "")) in {"gaussian", "quadratic", "soft_axis"}
    ]


def plot_model_partial_boxes(rows: list[dict]) -> None:
    filtered = [
        row for row in finite_metric_rows(rows)
        if row_best(row, "test_mse") <= 5e-3
        and model_group(row) in {"RF-LR low", "RF-LR high", "MLP"}
    ]
    if not filtered:
        return
    groups = ["RF-LR low", "RF-LR high", "MLP"]
    distributions = ["unpaired_uniform", "positive_bias"]
    colors = {"RF-LR low": "#2A6FBB", "RF-LR high": "#D95F02", "MLP": "#6A6A6A"}
    fig, axes = plt.subplots(1, len(distributions), figsize=(3.35, 1.9), sharey=True)
    if len(distributions) == 1:
        axes = [axes]
    for ax, dist in zip(axes, distributions):
        vals = []
        labels = []
        for group in groups:
            v = [
                row_best(row, "last_partial_neg_defect") + EPS
                for row in filtered
                if model_group(row) == group and str(row.get("train_distribution", "")) == dist
            ]
            vals.append(v)
            labels.append(f"{group}\n(n={len(v)})")
        positions = np.arange(1, len(groups) + 1)
        nonempty = [v if v else [np.nan] for v in vals]
        bp = ax.boxplot(nonempty, positions=positions, widths=0.56, patch_artist=True, showfliers=False)
        for patch, group in zip(bp["boxes"], groups):
            patch.set(facecolor=colors[group], alpha=0.75, edgecolor="#222222", linewidth=0.55)
        for median in bp["medians"]:
            median.set(color="white", linewidth=1.0)
        for pos, v, group in zip(positions, vals, groups):
            if v:
                jitter = np.linspace(-0.12, 0.12, len(v)) if len(v) > 1 else np.array([0.0])
                ax.scatter(pos + jitter, v, s=10, color=colors[group], edgecolor="white", linewidth=0.25, zorder=3)
        ax.set_yscale("log")
        ax.set_xticks(positions, labels, fontsize=5.3)
        title = "unpaired uniform" if dist == "unpaired_uniform" else "positive bias"
        ax.set_title(title, fontsize=7.2, pad=1.2)
        ax.grid(True, axis="y", which="major", color="#D9D9D9", linewidth=0.35, alpha=0.75)
        ax.grid(True, axis="y", which="minor", color="#EEEEEE", linewidth=0.18, alpha=0.55)
        ax.tick_params(axis="y", labelsize=5.8, length=2.0)
    axes[0].set_ylabel("active $D_p(-x)$", fontsize=7)
    fig.tight_layout(pad=0.1, w_pad=0.25)
    fig.savefig(OUT / "paper_model_partial_boxes.png", bbox_inches="tight", pad_inches=0.012)
    plt.close(fig)


def plot_positive_bias_dashboard(rows: list[dict]) -> None:
    filtered = [
        row for row in finite_metric_rows(rows)
        if str(row.get("train_distribution", "")) == "positive_bias"
        and model_group(row) in {"RF-LR low", "RF-LR high", "MLP"}
    ]
    if not filtered:
        return
    colors = {"gaussian": "#1B9E77", "quadratic": "#2A6FBB", "soft_axis": "#D95F02"}
    markers = {"RF-LR low": "o", "RF-LR high": "s", "MLP": "^"}
    fig, axes = plt.subplots(1, 2, figsize=(3.35, 1.92), sharey=True)
    for ax, dim in zip(axes, [2, 3]):
        for row in filtered:
            if int(row.get("dim", 0)) != dim:
                continue
            group = model_group(row)
            target = str(row.get("target"))
            ax.scatter(
                row_best(row, "test_mse") + EPS,
                row_best(row, "last_partial_neg_defect") + EPS,
                s=24 if group == "RF-LR low" else 30,
                marker=markers[group],
                color=colors.get(target, "#666666"),
                edgecolor="white",
                linewidth=0.45,
                alpha=0.88,
            )
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_title(f"{dim}D positive bias", fontsize=7.0, pad=1.0)
        ax.set_xlabel("test MSE", fontsize=7)
        ax.tick_params(axis="both", labelsize=5.8, length=2.0)
        ax.grid(True, which="major", color="#D9D9D9", linewidth=0.35, alpha=0.75)
        ax.grid(True, which="minor", color="#EEEEEE", linewidth=0.18, alpha=0.55)
    axes[0].set_ylabel("active $D_p(-x)$", fontsize=7)
    handles = [
        plt.Line2D([], [], marker=markers["RF-LR low"], linestyle="", color="#555555", markeredgecolor="white", label="low rank"),
        plt.Line2D([], [], marker=markers["RF-LR high"], linestyle="", color="#555555", markeredgecolor="white", label="high rank"),
        plt.Line2D([], [], marker=markers["MLP"], linestyle="", color="#555555", markeredgecolor="white", label="MLP"),
    ]
    fig.legend(handles=handles, loc="lower center", ncol=3, fontsize=5.6, bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout(pad=0.1, w_pad=0.25, rect=(0, 0.08, 1, 1))
    fig.savefig(OUT / "paper_positive_bias_dashboard.png", bbox_inches="tight", pad_inches=0.012)
    plt.close(fig)


def plot_multidim_dashboard(rows: list[dict]) -> None:
    filtered = [row for row in rows if is_main_row(row) and np.isfinite(value(row, "best_test_mse"))]
    palette = {2: "#2A6FBB", 3: "#D95F02"}
    markers = {True: "o", False: "s"}
    fig, axes = plt.subplots(3, 1, figsize=(3.25, 5.45), constrained_layout=True)

    def draw(ax: plt.Axes, x_key: str, y_key: str, xlabel: str, ylabel: str) -> None:
        for row in filtered:
            dim = int(row["dim"])
            rank = int(row.get("rank", 0))
            low_rank = rank in {8, 16}
            ax.scatter(
                value(row, x_key) + EPS,
                value(row, y_key) + EPS,
                s=24 if low_rank else 30,
                marker=markers[low_rank],
                facecolor=palette.get(dim, "#666666"),
                edgecolor="white",
                linewidth=0.45,
                alpha=0.9 if low_rank else 0.72,
            )
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlabel(xlabel, fontsize=7)
        ax.set_ylabel(ylabel, fontsize=7)
        ax.tick_params(axis="both", which="major", labelsize=6.5, length=2.5)
        ax.grid(True, which="major", color="#D9D9D9", linewidth=0.4, alpha=0.75)
        ax.grid(True, which="minor", color="#EEEEEE", linewidth=0.22, alpha=0.55)

    draw(axes[0], "best_test_mse", "best_output_neg_defect", "test MSE", r"$D_{out}(-x)$")
    draw(axes[1], "best_test_mse", "best_last_partial_neg_defect", "test MSE", r"$D_p(-x)$")
    draw(axes[2], "best_output_neg_defect", "best_last_partial_neg_defect", r"$D_{out}(-x)$", r"$D_p(-x)$")

    titles = ["fit gives output symmetry", "fit gives partial symmetry", "output symmetry is not enough"]
    for ax, title in zip(axes, titles):
        ax.set_title(title, fontsize=7.2, pad=1.3)

    handles = [
        plt.Line2D([], [], marker="o", linestyle="", color=palette[2], markeredgecolor="white", label="2D low-rank"),
        plt.Line2D([], [], marker="o", linestyle="", color=palette[3], markeredgecolor="white", label="3D low-rank"),
        plt.Line2D([], [], marker="s", linestyle="", color="#777777", markeredgecolor="white", label="high-rank"),
    ]
    fig.legend(handles=handles, loc="upper center", ncol=1, bbox_to_anchor=(0.5, 1.13), fontsize=7.2)
    fig.savefig(OUT / "paper_multidim_dashboard.png", bbox_inches="tight", pad_inches=0.015)
    plt.close(fig)

    plt.figure(figsize=(3.2, 1.75))
    draw(plt.gca(), "best_test_mse", "best_last_partial_neg_defect", "test MSE", r"$D_p(-x)$")
    plt.legend(handles=handles, loc="best", fontsize=7)
    plt.savefig(OUT / "paper_loss_vs_partial.png")
    plt.close()


def plot_representative_result_bars(rows: list[dict]) -> None:
    selected = representative_result_rows(rows)
    if not selected:
        return
    labels = []
    colors = []
    metrics = {
        "test MSE": [],
        r"$D_{out}$": [],
        r"$D_p$": [],
    }
    for row in selected:
        dim = int(row["dim"])
        rank = int(row["rank"])
        target = str(row["target"]).replace("soft_axis", "soft")
        label = f"{dim}D {target}\nr{rank}"
        labels.append(label)
        colors.append("#2A6FBB" if rank in {8, 16} else "#D95F02")
        metrics["test MSE"].append(value(row, "best_test_mse") + EPS)
        metrics[r"$D_{out}$"].append(value(row, "best_output_neg_defect") + EPS)
        metrics[r"$D_p$"].append(value(row, "best_last_partial_neg_defect") + EPS)

    y = np.arange(len(labels))
    fig, axes = plt.subplots(1, 3, figsize=(3.35, 2.28), sharey=True)
    for ax, (title, vals) in zip(axes, metrics.items()):
        ax.barh(y, vals, color=colors, edgecolor="white", linewidth=0.4, height=0.72)
        ax.set_xscale("log")
        ax.set_title(title, fontsize=7.2, pad=1.5)
        ax.grid(True, axis="x", which="major", color="#D9D9D9", linewidth=0.38, alpha=0.8)
        ax.grid(True, axis="x", which="minor", color="#EEEEEE", linewidth=0.2, alpha=0.55)
        ax.tick_params(axis="x", which="major", labelsize=5.9, length=2.2)
        ax.tick_params(axis="y", length=0)
    axes[0].set_yticks(y, labels)
    axes[0].tick_params(axis="y", labelsize=5.8)
    for ax in axes[1:]:
        ax.tick_params(axis="y", labelleft=False)
    axes[0].invert_yaxis()
    handles = [
        plt.Line2D([], [], marker="s", linestyle="", color="#2A6FBB", label="low rank"),
        plt.Line2D([], [], marker="s", linestyle="", color="#D95F02", label="high rank"),
    ]
    fig.legend(handles=handles, loc="lower center", ncol=2, fontsize=6.2, bbox_to_anchor=(0.58, -0.03))
    fig.tight_layout(pad=0.12, w_pad=0.28)
    fig.savefig(OUT / "paper_representative_bars.png", bbox_inches="tight", pad_inches=0.015)
    plt.close(fig)


def plot_rank_bars(rows: list[dict]) -> None:
    filtered = [
        row for row in rows
        if is_main_row(row)
        and str(row.get("target")) == "quadratic"
        and int(row.get("dim", 0)) in {2, 3}
        and int(row.get("rank", 0)) in {8, 16, 128}
    ]
    ranks = [8, 16, 128]
    x = np.arange(len(ranks))
    width = 0.34
    vals_2d = []
    vals_3d = []
    for rank in ranks:
        vals_2d.append(np.nanmedian([value(r, "best_last_partial_neg_defect") for r in filtered if int(r["dim"]) == 2 and int(r["rank"]) == rank]))
        vals_3d.append(np.nanmedian([value(r, "best_last_partial_neg_defect") for r in filtered if int(r["dim"]) == 3 and int(r["rank"]) == rank]))
    plt.figure(figsize=(3.35, 2.55))
    plt.bar(x - width / 2, np.asarray(vals_2d) + EPS, width, label="2D", color="#2A6FBB", edgecolor="white", linewidth=0.5)
    plt.bar(x + width / 2, np.asarray(vals_3d) + EPS, width, label="3D", color="#D95F02", edgecolor="white", linewidth=0.5)
    plt.yscale("log")
    plt.xticks(x, [str(r) for r in ranks])
    plt.xlabel("rank", fontsize=7)
    plt.ylabel(r"median $D_p$", fontsize=7)
    plt.tick_params(axis="both", which="major", labelsize=6.5, length=2.5)
    plt.grid(True, axis="y", which="major", color="#D9D9D9", linewidth=0.4, alpha=0.8)
    plt.grid(True, axis="y", which="minor", color="#EEEEEE", linewidth=0.22, alpha=0.55)
    plt.legend(loc="upper left", fontsize=6.5)
    plt.tight_layout(pad=0.18)
    plt.savefig(OUT / "paper_rank_vs_partial.png", bbox_inches="tight", pad_inches=0.015)
    plt.close()


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    apply_style()
    rows = read_rows()
    write_aggregate(rows)
    write_tables(rows)
    plot_sumcos_targets()
    plot_sumcos_low_loss()
    plot_weightspace_regimes()
    plot_weightspace_class_summary()
    plot_multidim_dashboard(rows)
    plot_model_partial_boxes(rows)
    plot_positive_bias_dashboard(rows)
    plot_representative_result_bars(rows)
    plot_rank_bars(rows)
    print(f"built {len(rows)} rows -> {OUT}")


if __name__ == "__main__":
    main()
