interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [
    ".",
]

[[modules ]]
path = "model"
depends_on = []

[[modules ]]
path = "model.mmnn"
depends_on = []

[[modules ]]
path = "model.ntk"
depends_on = []
